### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by ZeFish** [irbull/obsidian-ai-summary#6]
sadly it doesn't work anymore

**Comment by irbull** [comment]
:(. Do you have any error message? I can take a look.

**Comment by ZeFish** [comment]
<img width="930" alt="Screenshot 2024-11-06 at 11 27 12 AM" src="https://github.com/user-attachments/assets/a6dda5c3-cbf3-4d5a-a093-2f0a04c145fd">
I don't know what and where I can find logs that could help you

**Comment by irbull** [comment]
Thanks for reporting. Looks like the version number in the `manifest.json` didn't match the release I had. I've updated the version and re-ran the release pipelines. Looks like it works now. Thanks again!
